from __future__ import annotations

from dataclasses import dataclass

from content.faqs import area_faqs
from content.images import IMAGES


@dataclass(frozen=True)
class Area:
    slug: str
    label: str
    area_type: str
    title: str
    description: str
    intro: str
    neighborhoods: tuple[str, ...]
    housing: str
    common_repairs: tuple[str, ...]
    nearby_slugs: tuple[str, ...]
    image_key: str

    @property
    def faqs(self) -> tuple[tuple[str, str], ...]:
        return area_faqs(self.slug, self.label, self.area_type, self.neighborhoods, self.housing)


AREAS: tuple[Area, ...] = (
    Area(
        "springfield", "Springfield", "city",
        "Springfield MO Handyman | Premium Repairs for Ozarks Homes",
        "Upscale handyman services in Springfield, Missouri for drywall, doors, decks, trim, cabinets, punch lists and estate maintenance.",
        "Springfield is the anchor of our service area. From mature neighborhoods near the center of town to newer estates on the edges of the metro, homes here span Craftsman bungalows, ranch homes, two-stories and upscale suburban properties. That variety creates steady demand for careful drywall repair, door tuning, trim restoration, deck maintenance and pre-sale punch lists. We understand the Ozarks climate patterns—humidity swings, storm seasons and freeze-thaw cycles—that affect doors, caulk lines, fences and exterior wood. Whether you own a primary residence, manage rentals or are preparing a home for market, Springfield homeowners benefit from a handyman approach that values finish quality, clear scope and respectful in-home work.",
        ("Rountree", "Phelps Grove", "Fremont Hills", "Southern Hills", "Brentwood", "Robberson", "Doling Park", "Grant Beach"),
        "a mix of historic bungalows, established family homes and newer upscale subdivisions",
        ("Whole-house punch lists before listing", "Historic-home door and trim adjustments", "Drywall and texture repair in finished living areas", "Deck and fence presentation repairs", "Rental turnover maintenance", "Cabinet hardware and hinge tuning", "Bath and kitchen caulk refresh", "TV mounting and shelving installs", "Inspection response repairs", "Seasonal exterior maintenance", "Move-in detail work for buyers", "Estate maintenance visits"),
        ("nixa", "ozark", "republic", "battlefield", "rountree", "phelps-grove"),
        "craftsman_bungalow",
    ),
    Area(
        "nixa", "Nixa", "city",
        "Nixa MO Handyman | Home Repairs for Growing Suburban Properties",
        "Handyman services in Nixa, Missouri for family homes, move-in punch lists, deck repair, fence repair and refined interior touch-ups.",
        "Nixa has grown into one of the most active suburban markets south of Springfield. Many homes here are newer builds with builder-grade hardware, fresh landscaping and outdoor living spaces that still need fine-tuning after move-in. Common requests include pantry shelving upgrades, cabinet hardware changes, door adjustments after settling, fence gate alignment and deck fastener maintenance. Nixa homeowners often want one reliable visit to handle the list that does not rise to full contractor scope but is too important to ignore.",
        ("Highlandville corridor", "north Nixa subdivisions", "south Nixa family neighborhoods", "Ozark-adjacent communities"),
        "newer suburban homes, family neighborhoods and larger lots with outdoor living spaces",
        ("Move-in punch lists", "Builder-grade hardware upgrades", "Deck and fence tune-ups", "Drywall anchor-hole repair", "Pantry and closet shelving", "Exterior caulk maintenance", "Pre-sale cosmetic repairs", "Garage storage installs", "Rental turnover items", "Storm-season exterior fixes", "Bath recaulking and fixture installs", "Interior door humidity adjustments"),
        ("springfield", "ozark", "republic", "battlefield"),
        "suburban_home",
    ),
    Area(
        "ozark", "Ozark", "city",
        "Ozark MO Handyman | Repairs for Suburban and Hillside Homes",
        "Handyman service in Ozark, Missouri for decks, fences, doors, drywall, trim and estate maintenance on Ozarks properties.",
        "Ozark combines suburban convenience with the rolling character of the Ozarks. Homes here often feature larger yards, decks, privacy fencing and multi-level interiors that benefit from ongoing maintenance. We frequently handle deck board replacement, gate repairs, exterior caulk refresh, interior trim touch-ups and move-in lists for buyers relocating into Christian County.",
        ("Finley Creek area neighborhoods", "north Ozark subdivisions", "south Ozark residential streets", "Nixa-adjacent pockets"),
        "suburban homes, hillside lots and outdoor-focused properties",
        ("Deck maintenance and railing repairs", "Privacy fence and gate fixes", "Door alignment after settling", "Exterior weather sealing", "Drywall repair in family spaces", "Shelving and storage upgrades", "Pre-listing punch lists", "Rental turnover repairs", "Fixture and hardware installs", "Storm damage touch-ups", "Kitchen and bath detail repairs", "Move-in buyer lists"),
        ("springfield", "nixa", "battlefield", "republic"),
        "deck_outdoor",
    ),
    Area(
        "republic", "Republic", "city",
        "Republic MO Handyman | Punch Lists and Home Detail Repairs",
        "Handyman services in Republic, Missouri for move-in repairs, rental turnovers, drywall, doors, trim and pre-sale home prep.",
        "Republic continues to attract families and commuters who want newer housing stock with quick access to Springfield. That creates strong demand for move-in punch lists, hardware upgrades, drywall repairs, cabinet tune-ups and pre-sale cosmetic fixes. Republic homes often need practical help turning builder-grade details into a more finished feel.",
        ("north Republic subdivisions", "south Republic family neighborhoods", "school-district adjacent streets", "growth corridors toward Springfield"),
        "newer subdivisions, commuter-family homes and growing rental stock",
        ("Move-in hardware and door adjustments", "Drywall repair after settling", "Pre-sale photo-ready repairs", "Rental turnover bundles", "Closet and pantry shelving", "Fence gate repairs", "Cabinet hinge tuning", "Bath caulk and fixture installs", "Deck safety fixes", "Garage organization projects", "Inspection response items", "Seasonal maintenance visits"),
        ("springfield", "battlefield", "willard", "nixa"),
        "suburban_home",
    ),
    Area(
        "battlefield", "Battlefield", "city",
        "Battlefield MO Handyman | Small Repairs and Estate Maintenance",
        "Handyman help in Battlefield, Missouri for drywall, doors, decks, fences, trim and punch-list repairs near Springfield.",
        "Battlefield offers a quieter suburban feel with convenient access to Springfield employers, shopping and services. Homeowners here often schedule handyman visits for mixed interior and exterior lists: sticking doors, loose trim, deck boards, fence gates, bath caulk and shelving installs. It is a strong fit for owners who want one polished visit rather than multiple small appointments.",
        ("Battlefield subdivisions", "north Battlefield neighborhoods", "Republic-adjacent streets", "commuter pockets toward Springfield"),
        "suburban family homes and well-kept residential neighborhoods",
        ("Mixed interior-exterior punch lists", "Door and trim adjustments", "Deck and fence repairs", "Drywall touch-ups", "Shelving and fixture installs", "Rental maintenance", "Pre-sale cosmetic fixes", "Kitchen and bath detail work", "Garage storage upgrades", "Seasonal caulk refresh", "Inspection repairs", "Move-in buyer lists"),
        ("springfield", "republic", "ozark", "willard"),
        "suburban_home",
    ),
    Area(
        "willard", "Willard", "city",
        "Willard MO Handyman | Rural-Suburban Home Repairs",
        "Handyman services in Willard, Missouri for family homes, acreage properties, decks, fences and practical maintenance lists.",
        "Willard blends suburban neighborhoods with a more rural Ozarks feel. Properties may include larger lots, detached workshops, decks, garden fencing and family interiors that need ongoing care. We help with practical repairs that keep homes comfortable, rentable and market-ready without unnecessary contractor overhead.",
        ("Willard city neighborhoods", "north Willard residential areas", "rural-suburban pockets", "northwest Greene County homes"),
        "family homes, larger lots and rural-suburban properties",
        ("Deck and fence maintenance", "Door and hardware repairs", "Drywall and trim touch-ups", "Shelving and garage storage", "Exterior caulk and sealing", "Rental and farmette maintenance", "Move-in punch lists", "Storm-season repairs", "Fixture installs", "Pre-sale prep", "Inspection items", "Seasonal maintenance bundles"),
        ("springfield", "republic", "strafford", "battlefield"),
        "ozarks_forest",
    ),
    Area(
        "strafford", "Strafford", "city",
        "Strafford MO Handyman | Maintenance for Ozarks Family Homes",
        "Handyman service in Strafford, Missouri for drywall, doors, exterior repairs, shelving and seasonal maintenance.",
        "Strafford homeowners often value straightforward communication and practical repairs done well. Requests commonly include interior finish repairs, door adjustments, cabinet hardware, exterior maintenance and storage upgrades for busy households.",
        ("Strafford residential core", "east Strafford neighborhoods", "nearby rural-suburban homes", "commuter routes toward Springfield"),
        "family homes and rural-suburban residences",
        ("Interior punch lists", "Door and trim repairs", "Drywall patching", "Shelving and storage", "Fence and gate fixes", "Deck maintenance", "Fixture installs", "Rental repairs", "Seasonal exterior prep", "Cabinet tune-ups", "Bath and kitchen caulk", "Move-in detail work"),
        ("springfield", "willard", "rogersville", "republic"),
        "ozarks_forest",
    ),
    Area(
        "rogersville", "Rogersville", "city",
        "Rogersville MO Handyman | Home Repair Near the Springfield Metro",
        "Handyman services in Rogersville, Missouri for punch lists, drywall, doors, decks, fences and property maintenance.",
        "Rogersville sits along key commuter routes and includes a mix of established homes and newer residential growth. Handyman work here often supports move-in lists, family-home maintenance, rental turnovers and pre-sale repairs for owners heading to or from the Springfield market.",
        ("Rogersville city neighborhoods", "commuter corridors", "nearby residential pockets", "Webster County edges"),
        "commuter homes, family residences and growing suburban pockets",
        ("Move-in and punch-list repairs", "Drywall and trim fixes", "Door and hardware adjustments", "Deck and fence touch-ups", "Shelving installs", "Rental turnovers", "Pre-sale prep", "Fixture upgrades", "Exterior caulk", "Inspection repairs", "Garage storage", "Seasonal maintenance"),
        ("springfield", "strafford", "nixa", "ozark"),
        "suburban_home",
    ),
    Area(
        "rountree", "Rountree", "neighborhood",
        "Rountree Springfield Handyman | Historic Home Repairs and Finish Work",
        "Handyman service in Rountree, Springfield for historic-home drywall, trim, doors, hardware and pre-sale punch lists.",
        "Rountree is known for walkable streets and charming older homes with character details that deserve careful repair. We often handle plaster-adjacent drywall issues, door alignment in older frames, trim repairs, hardware upgrades and pre-listing cosmetic fixes that respect the home's original feel.",
        ("Rountree Historic District streets", "Cherokee Estates", "near Phelps Grove", "adjacent central Springfield blocks"),
        "historic bungalows, early 20th-century homes and walkable neighborhood properties",
        ("Older-home door alignment", "Trim and casing repair", "Drywall patches in finished rooms", "Pre-sale cosmetic fixes", "Hardware upgrades", "Deck and porch touch-ups", "Fence gate repairs", "Bath and kitchen caulk", "Shelving and storage", "Inspection response items", "Rental maintenance", "Interior punch lists"),
        ("springfield", "phelps-grove", "brentwood", "walnut-street"),
        "craftsman_bungalow",
    ),
    Area(
        "phelps-grove", "Phelps Grove", "neighborhood",
        "Phelps Grove Handyman | Refined Repairs Near MSU and Cherry Street",
        "Handyman services in Phelps Grove for condos, bungalows, rentals and owner-occupied homes near Springfield's central corridor.",
        "Phelps Grove includes a mix of owner-occupied homes, rentals and properties influenced by nearby Missouri State University activity. Repairs often include drywall touch-ups, door and hardware fixes, trim repair, fixture installs and turnover work for landlords.",
        ("Phelps Grove core", "MSU-adjacent streets", "Cherry Street corridor homes", "near Rountree and Southern Hills"),
        "bungalows, duplexes, rentals and updated owner-occupied homes",
        ("Rental turnover repairs", "Drywall and trim touch-ups", "Door and hardware fixes", "Fixture and shelving installs", "Pre-leasing cosmetic repairs", "Kitchen and bath refresh items", "Deck and porch maintenance", "Fence repairs", "Move-in lists", "Inspection repairs", "Cabinet hinge tuning", "Seasonal maintenance"),
        ("springfield", "rountree", "southern-hills", "walnut-street"),
        "craftsman_bungalow",
    ),
    Area(
        "fremont-hills", "Fremont Hills", "neighborhood",
        "Fremont Hills Handyman | Estate Maintenance and Premium Finish Repairs",
        "Handyman service in Fremont Hills for upscale homes needing drywall, trim, deck, cabinet, mounting and pre-sale prep work.",
        "Fremont Hills is one of Springfield's most recognized upscale neighborhoods. Homeowners here often expect refined communication, protected finished spaces and detail work that supports high presentation standards. Common projects include trim and drywall touch-ups, cabinet hardware upgrades, deck maintenance, custom shelving and listing prep.",
        ("Fremont Hills estates", "adjacent south Springfield subdivisions", "near Southern Hills", "premium residential streets"),
        "upscale single-family homes and well-maintained suburban estates",
        ("Pre-sale punch lists", "Trim and drywall finish repairs", "Cabinet hardware upgrades", "Deck and exterior presentation", "Custom shelving and storage", "TV and fixture installation", "Door and hardware tuning", "Bath and kitchen caulk refresh", "Fence gate repairs", "Inspection response items", "Estate maintenance visits", "Move-in detail upgrades"),
        ("springfield", "southern-hills", "ozark", "nixa"),
        "executive_home",
    ),
    Area(
        "southern-hills", "Southern Hills", "neighborhood",
        "Southern Hills Handyman | Family Home Repairs and Outdoor Maintenance",
        "Handyman services in Southern Hills for family homes, decks, fences, drywall, doors and seasonal maintenance.",
        "Southern Hills features established family homes with mature landscaping and outdoor spaces that need ongoing care. We commonly repair decks, fences, interior trim, doors affected by humidity and mixed punch lists for busy households.",
        ("Southern Hills core", "adjacent south Springfield blocks", "near Phelps Grove", "family residential streets"),
        "established family homes with decks, fences and finished interiors",
        ("Deck and fence maintenance", "Door humidity adjustments", "Drywall and trim repairs", "Garage and storage upgrades", "Fixture and shelving installs", "Pre-sale cosmetic repairs", "Rental maintenance", "Kitchen and bath caulk", "Storm-season touch-ups", "Inspection repairs", "Move-in lists", "Seasonal maintenance bundles"),
        ("springfield", "phelps-grove", "fremont-hills", "brentwood"),
        "traditional_estate",
    ),
    Area(
        "brentwood", "Brentwood", "neighborhood",
        "Brentwood Springfield Handyman | Interior and Exterior Detail Repairs",
        "Handyman help in Brentwood, Springfield for drywall, trim, doors, fencing and practical home maintenance.",
        "Brentwood offers a mix of mid-century and updated family homes that often need practical handyman help: drywall repairs, door tuning, trim restoration, fence gate fixes and pre-sale cosmetic improvements.",
        ("Brentwood North", "Brentwood South", "adjacent central neighborhoods", "near Rountree and Robberson"),
        "mid-century and updated family homes in established neighborhoods",
        ("Interior punch lists", "Drywall and trim repair", "Door and hardware fixes", "Fence gate repairs", "Deck maintenance", "Fixture installs", "Rental turnovers", "Pre-sale prep", "Kitchen and bath caulk", "Shelving upgrades", "Inspection items", "Move-in repairs"),
        ("springfield", "rountree", "roberson", "phelps-grove"),
        "suburban_home",
    ),
    Area(
        "roberson", "Robberson", "neighborhood",
        "Robberson Handyman | Practical Repairs for Central Springfield Homes",
        "Handyman services in the Robberson neighborhood for drywall, doors, trim, rentals and owner-occupied home maintenance.",
        "Robberson includes a blend of rentals and long-term owner-occupied homes. That creates demand for turnover repairs, interior finish fixes, hardware upgrades and practical maintenance that keeps properties comfortable and marketable.",
        ("Robberson core", "near Grant Beach", "adjacent central Springfield blocks", "Brentwood edges"),
        "owner-occupied homes, rentals and mixed residential stock",
        ("Rental turnover repairs", "Drywall patching", "Door and hardware fixes", "Trim and caulk touch-ups", "Fixture installs", "Fence and porch repairs", "Pre-leasing cosmetic work", "Move-in lists", "Inspection repairs", "Cabinet hinge tuning", "Shelving installs", "Seasonal maintenance"),
        ("springfield", "brentwood", "grant-beach", "doling-park"),
        "suburban_home",
    ),
    Area(
        "doling-park", "Doling Park", "neighborhood",
        "Doling Park Handyman | Home Repairs in North Springfield",
        "Handyman service in the Doling Park area for drywall, doors, decks, fences and affordable home maintenance.",
        "The Doling Park area includes family homes and older housing stock that benefit from practical repairs and upkeep. Common work includes drywall patching, door adjustments, deck and fence maintenance, fixture installs and rental repairs.",
        ("Doling Park neighborhood", "north Springfield residential blocks", "near Grant Beach", "adjacent family-home streets"),
        "family homes and older residential properties",
        ("Drywall and trim repairs", "Door and hardware fixes", "Deck and fence maintenance", "Fixture and shelving installs", "Rental repairs", "Pre-sale cosmetic fixes", "Kitchen and bath caulk", "Garage storage", "Inspection items", "Move-in lists", "Storm-season touch-ups", "Seasonal maintenance"),
        ("springfield", "grant-beach", "roberson", "willard"),
        "suburban_home",
    ),
    Area(
        "grant-beach", "Grant Beach", "neighborhood",
        "Grant Beach Handyman | Repairs for North Springfield Neighborhood Homes",
        "Handyman services in Grant Beach for drywall, doors, trim, fencing and practical rental or owner-occupied repairs.",
        "Grant Beach homeowners and landlords often need efficient repairs that improve comfort and presentation without major renovation scope. We handle mixed lists that keep properties functional and ready for daily use or turnover.",
        ("Grant Beach core", "north Springfield blocks", "near Doling Park", "adjacent residential streets"),
        "owner-occupied homes, rentals and established neighborhood housing",
        ("Rental turnover repairs", "Drywall patching", "Door and hardware fixes", "Fence and gate repairs", "Fixture installs", "Trim and caulk touch-ups", "Deck maintenance", "Pre-sale cosmetic repairs", "Shelving upgrades", "Inspection items", "Move-in lists", "Seasonal maintenance"),
        ("springfield", "doling-park", "roberson", "willard"),
        "suburban_home",
    ),
    Area(
        "walnut-street", "Walnut Street District", "neighborhood",
        "Walnut Street District Handyman | Downtown-Adjacent Home Repairs",
        "Handyman services near Springfield's Walnut Street district for condos, townhomes, rentals and updated urban-adjacent residences.",
        "The Walnut Street corridor and nearby downtown-adjacent neighborhoods include condos, townhomes and renovated residences that need detail-oriented repairs. We handle drywall, hardware, trim, mounting and turnover work with respect for tighter spaces and parking logistics.",
        ("Walnut Street corridor", "downtown-adjacent blocks", "near Phelps Grove", "central Springfield infill homes"),
        "condos, townhomes, rentals and renovated urban-adjacent residences",
        ("Condo and townhome punch lists", "Drywall and trim touch-ups", "Fixture and TV mounting", "Door and hardware repairs", "Rental turnover items", "Kitchen and bath caulk", "Shelving and storage", "Pre-sale cosmetic fixes", "Cabinet hinge tuning", "Inspection repairs", "Move-in lists", "Interior detail maintenance"),
        ("springfield", "phelps-grove", "rountree", "brentwood"),
        "refined_interior",
    ),
    Area(
        "woodhurst", "Woodhurst", "neighborhood",
        "Woodhurst Handyman | Suburban Home Repairs in Southwest Springfield",
        "Handyman services in Woodhurst for family homes, decks, fences, drywall, doors and move-in punch lists.",
        "Woodhurst is a well-known southwest Springfield neighborhood with family homes that often need practical maintenance: door adjustments, deck repairs, fence gate fixes, interior trim and move-in punch lists for new owners.",
        ("Woodhurst core", "southwest Springfield subdivisions", "near Southern Hills", "family residential streets"),
        "family homes, suburban residences and outdoor living spaces",
        ("Move-in punch lists", "Deck and fence repairs", "Door and trim adjustments", "Drywall patching", "Fixture and shelving installs", "Pre-sale cosmetic repairs", "Kitchen and bath caulk", "Garage storage", "Inspection items", "Rental maintenance", "Cabinet hardware tuning", "Seasonal maintenance"),
        ("springfield", "southern-hills", "fremont-hills", "battlefield"),
        "deck_outdoor",
    ),
    Area(
        "marshfield", "Marshfield", "city",
        "Marshfield MO Handyman | Home Repairs West of the Springfield Metro",
        "Handyman services in Marshfield, Missouri for rural-suburban homes, seasonal maintenance and practical repair lists.",
        "Marshfield extends our reach for homeowners west of Springfield who want the same refined repair approach on acreage properties, family homes and seasonal maintenance lists.",
        ("Marshfield city neighborhoods", "Webster County residential areas", "rural-suburban pockets", "commuter routes toward Springfield"),
        "family homes, acreage properties and rural-suburban residences",
        ("Deck and fence maintenance", "Exterior caulk and sealing", "Interior punch lists", "Door and hardware repairs", "Drywall and trim touch-ups", "Shelving and storage installs", "Storm-season repairs", "Rental maintenance", "Fixture installs", "Pre-sale prep", "Gutter tune-ups", "Seasonal maintenance bundles"),
        ("springfield", "willard", "strafford", "rogersville"),
        "ozarks_forest",
    ),
    Area(
        "clever", "Clever", "city",
        "Clever MO Handyman | Repairs for Christian County Homes",
        "Handyman services in Clever, Missouri for suburban and rural-suburban repair lists, decks, fences and interior detail work.",
        "Clever homeowners often need practical mixed repairs across interior and exterior spaces on family properties between Springfield and the growing Christian County corridor.",
        ("Clever residential core", "near Nixa and Ozark", "Christian County neighborhoods", "rural-suburban streets"),
        "family homes, rural-suburban properties and commuter residences",
        ("Fence and deck repairs", "Drywall and trim touch-ups", "Door adjustments", "Storm repairs", "Shelving installs", "Rental touch-ups", "Fixture installs", "Screen repair", "Caulk refresh", "Punch lists", "Move-in repairs", "Seasonal maintenance"),
        ("nixa", "ozark", "springfield", "republic"),
        "ozarks_hills",
    ),
    Area(
        "del-lago", "Del Lago", "neighborhood",
        "Del Lago Handyman | Executive Home Repairs in Southwest Springfield",
        "Handyman services in Del Lago for executive homes, estate maintenance, fixture upgrades and refined finish repairs.",
        "Del Lago homeowners often expect discretion, neat job sites and careful finish work across mixed repair lists in an executive subdivision setting.",
        ("Del Lago estates", "adjacent southwest Springfield subdivisions", "near Southern Hills", "premium residential streets"),
        "executive subdivision homes with higher finish standards and larger maintenance lists",
        ("Estate maintenance visits", "Fixture and hardware upgrades", "Deck and fence care", "Interior paint touch-ups", "Cabinet tuning", "Custom shelving", "Pre-sale polish", "Storm repairs", "Screen and caulk refresh", "Whole-home tune-ups", "Guest house punch lists", "Seasonal exterior detail"),
        ("springfield", "fremont-hills", "southern-hills", "woodhurst"),
        "traditional_estate",
    ),
    Area(
        "highland-springs", "Highland Springs", "neighborhood",
        "Highland Springs Handyman | Family Home Repairs in Springfield",
        "Handyman services in Highland Springs for family homes, move-in lists, drywall, doors and suburban maintenance.",
        "Highland Springs area properties benefit from bundled repair visits that cover doors, drywall, trim, exterior wear and move-in adjustments.",
        ("Highland Springs subdivisions", "southwest Springfield family neighborhoods", "near Republic corridor", "adjacent suburban streets"),
        "family suburban housing with routine maintenance and move-in repair needs",
        ("Move-in repairs", "Door adjustments", "Drywall patches", "Fence gate fixes", "Deck maintenance", "Fixture installs", "Rental touch-ups", "Shelving upgrades", "Caulk refresh", "Punch lists", "Pre-sale cosmetic fixes", "Seasonal maintenance"),
        ("springfield", "republic", "nixa", "battlefield"),
        "suburban_home",
    ),
    Area(
        "spring-creek", "Spring Creek", "neighborhood",
        "Spring Creek Handyman | Newer Home Repairs in Springfield",
        "Handyman services in the Spring Creek area for newer homes, warranty-period adjustments and move-in punch lists.",
        "Spring Creek area homes often need builder punch-list help, hardware tuning, cabinet adjustments and move-in detail work after purchase.",
        ("Spring Creek subdivisions", "southwest Springfield growth areas", "near Republic", "newer family-home streets"),
        "newer subdivisions and family homes with punch-list and move-in repair needs",
        ("Move-in punch lists", "Hardware installs", "Drywall touch-ups", "Cabinet adjustments", "Caulk and trim work", "Shelving installs", "Fence and deck touch-ups", "Fixture installs", "Pre-sale polish", "Inspection items", "Garage storage", "Seasonal maintenance"),
        ("springfield", "republic", "highland-springs", "battlefield"),
        "suburban_home",
    ),
    Area(
        "wilson-creek", "Wilson's Creek", "neighborhood",
        "Wilson's Creek Handyman | Suburban Repairs in Southwest Springfield",
        "Handyman services in the Wilson's Creek area for family homes, decks, fences, drywall and mixed maintenance lists.",
        "The Wilson's Creek area includes family neighborhoods where decks, fences, interior wear and seasonal maintenance create steady handyman demand.",
        ("Wilson's Creek area neighborhoods", "southwest Springfield suburbs", "near Republic and Battlefield", "family residential pockets"),
        "suburban family housing with outdoor living spaces and routine maintenance needs",
        ("Deck repairs", "Fence gates", "Interior punch lists", "Drywall patches", "Door tune-ups", "Storm repairs", "Fixture installs", "Rental touch-ups", "Gutter fixes", "Shelving installs", "Pre-sale polish", "Seasonal maintenance"),
        ("springfield", "battlefield", "republic", "southern-hills"),
        "deck_outdoor",
    ),
)

AREA_BY_SLUG = {area.slug: area for area in AREAS}
CITY_AREAS = [area for area in AREAS if area.area_type == "city"]
NEIGHBORHOOD_AREAS = [area for area in AREAS if area.area_type == "neighborhood"]
